CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS tickets (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS entries (id INTEGER PRIMARY KEY, name TEXT);
